#!/bin/sh
USAGE="Usage: $0 in.pgm [out.vtk]"
if [ $# -lt 1 ]
then
	echo $USAGE
        exit
fi
if [ $# -gt 2 ]
then
	echo $USAGE
        exit
fi
3dkhalimskize $1 h /tmp/visu1pgm_1
3dborder /tmp/visu1pgm_1 /tmp/visu1pgm_1
if [ $# -eq 1 ]
then
    pgm2vtk /tmp/visu1pgm_1 1 /tmp/visu1pgm_1.vtk
    multirender /tmp/visu1pgm_1.vtk
fi
if [ $# -eq 2 ]
then
    pgm2vtk /tmp/visu1pgm_1 1 $2
fi
rm -f /tmp/visu1pgm_*
