#!/usr/bin/python
import sys
import os
import re

# print 'Number of arguments:', len(sys.argv), 'arguments.'
# print 'Argument List:', str(sys.argv)

if (len(sys.argv) != 3) : 
    print "usage: cmdname in out"
    sys.exit ()

name = sys.argv[0]
infilename = sys.argv[1]
outfilename = sys.argv[2]
tmpprefix = "/tmp/"

# PROCEDURES UTILES
#-----------------------------------

# reads a list of data from a file
#-----------------------------------
def my_readlistdata(filename) :
  f = open(filename, 'r')
  l = f.readline().split()
  tag = l[0]
  n = l[1]
  r = []
  for i in range(1,int(n)+1):
    l = f.readline().split()
    r.append(l)
  return r


# reads a pgm image header
# returns the image sizes in the form of a list : [rowsize, colsize] (in 2D)
# or [rowsize, colsize, depth] in 3D
#-----------------------------------
def my_readpgmheader(filename) :
  f = open(filename, 'r')
  # read tag
  s = f.readline()
  # skip comment lines and reads one more line
  l = f.readline().split()
  while (l[0][0] == '#') or (len(l) == 0) :    
    l = f.readline().split()
  return l

# executes a shell command (quiet)
#-----------------------------------
def my_exec(command, *args) :
  s = command
  for arg in args:
    s = s+" "+str(arg)
  os.system(s)

# executes a shell command (verbose)
#-----------------------------------
def my_exec_v(command, *args) :
  s = command
  for arg in args:
    s = s+" "+str(arg)
  print s
  os.system(s)
