#!/bin/sh
USAGE="Usage: $0 i1 i2 factor out"
if [ $# -gt 4 ]
then
	echo $USAGE
        exit
fi
if [ $# -lt 4 ]
then
	echo $USAGE
        exit
fi

scale $1 $3 /tmp/_combine_1
max /tmp/_combine_1 $2 $4
inverse $4 $4

rm /tmp/_combine_?
