#!/bin/sh
USAGE="Usage: $0 in connex out"
if [ $# -gt 3 ]
then
	echo $USAGE
        exit
fi
if [ $# -lt 3 ]
then
	echo $USAGE
        exit
fi
topotypes $1 1 $2 _$1.1
selndg _$1.1 2 2 _$1.1
seuilbin _$1.1 1 _$1.1
uniconnectant $1 4 _$1.2
inverse _$1.2  _$1.2 
sub _$1.1 _$1.2 _$1.3
sub $1 _$1.3 $3
rm          _$1.?
