#!/bin/sh
USAGE="Usage: $0 in n out"
if [ $# -gt 3 ]
then
	echo $USAGE
        exit
fi
if [ $# -lt 3 ]
then
	echo $USAGE
        exit
fi
hthick3d      $1      null       6         $2   _$1.tmp 
deletewells  _$1.tmp    6        _$1.tmp
htkern3d     _$1.tmp    $1       6         $3
rm           _$1.tmp

