#!/bin/sh
USAGE="Usage: $0 in connex out"
if [ $# -gt 3 ]
then
	echo $USAGE
        exit
fi
if [ $# -lt 3 ]
then
	echo $USAGE
        exit
fi
label $1 $2 max _$1.1
long2byte _$1.1 3 2 _$1.1 
seuilbin _$1.1 1 $3
rm _$1.1
