#!/bin/sh
USAGE="Usage: $0 in n <alpha|delta> out"
if [ $# -gt 4 ]
then
	echo $USAGE
        exit
fi
if [ $# -lt 4 ]
then
	echo $USAGE
        exit
fi
lthin         $1      null       4         $2      $3      _$1.tmp 
htkernu      _$1.tmp    $1       4         $4
changename    $4     "lfiltrepics4($1,$2,$3)"
rm           _$1.tmp

