#!/bin/sh
# =======================================================================
# Segmentation de pastilles Mox (zones U)
# Methode : seuillage du reseau de transitions 
#           et obtention de marqueurs avec la fonction distance
# =======================================================================
USAGE="Usage: $0 in out"
if [ $# -gt 2 ]
then
	echo $USAGE
        exit
fi
if [ $# -lt 2 ]
then
	echo $USAGE
        exit
fi
deriche $1 1 3 0.5 _segmox1.r
deriche _segmox1.r 1 0 _segmox1.gr
seuilbin _segmox1.gr 18 _segmox1.sgr
attribute _segmox1.sgr 4 20000 max area _segmox1.asgr
seuilbin _segmox1.asgr 1 _segmox1.asgr
dist _segmox1.asgr 0 _segmox1.dasgr
long2byte _segmox1.dasgr _segmox1.dasgr
inverse _segmox1.dasgr _segmox1.dasgr
segment _segmox1.dasgr 4 2 _segmox1.sdasgr
inverse $1 _segmox1.i
propgeo _segmox1.i _segmox1.sdasgr 4 min1 _segmox1.psdasgr
lpemeyer _segmox1.i _segmox1.psdasgr $2
