#!/bin/sh
USAGE="Usage: $0 in n out"
if [ $# -gt 3 ]
then
	echo $USAGE
        exit
fi
if [ $# -lt 3 ]
then
	echo $USAGE
        exit
fi
inverse $1 /tmp/SHRINKC_1 
dist /tmp/SHRINKC_1 0 /tmp/SHRINKC_d 
medialaxis $1 /tmp/SHRINKC_d 0 /tmp/SHRINKC_1 
cadre $1 /tmp/SHRINKC_3
long2byte /tmp/SHRINKC_d /tmp/SHRINKC_d 
min /tmp/SHRINKC_d /tmp/SHRINKC_3 /tmp/SHRINKC_3
max /tmp/SHRINKC_3 /tmp/SHRINKC_1 /tmp/SHRINKC_1
seuil /tmp/SHRINKC_1 1 /tmp/SHRINKC_2
hthin $1 /tmp/SHRINKC_2 4 -1 delta /tmp/SHRINKC_2
hthin /tmp/SHRINKC_2 null 4 $2 delta /tmp/SHRINKC_2
min /tmp/SHRINKC_2 /tmp/SHRINKC_1 /tmp/SHRINKC_2
medialaxis /tmp/SHRINKC_2 0 1 $3
seuil $3 1 $3
rm -f /tmp/SHRINKC_?
