#!/bin/sh
USAGE="Usage: $0 in out.gif"
if [ $# -gt 2 ]
then
	echo $USAGE
        exit
fi
if [ $# -lt 2 ]
then
	echo $USAGE
        exit
fi
convert      $1 _$1.ppm
ppm2pgm      _$1.ppm _$1.r _$1.g _$1.b
convol       _$1.r $PINK/masks/vois8.pgm _$1.r
convol       _$1.g $PINK/masks/vois8.pgm _$1.g
convol       _$1.b $PINK/masks/vois8.pgm _$1.b
pgm2ppm      _$1.r _$1.g _$1.b _$2.ppm
convert      _$2.ppm $2
gifsicle     $2 -O -o $2
rm          _$1.r _$1.g _$1.b _$1.ppm _$2.ppm

