#!/bin/sh
USAGE="Usage: $0 in connex out"
if [ $# -gt 3 ]
then
	echo $USAGE
        exit
fi
if [ $# -lt 3 ]
then
	echo $USAGE
        exit
fi
cadre $1 _$1.1
inverse $1 _$1.2
reconsdilat _$1.1 _$1.2 $2 _$1.3
sub _$1.2 _$1.3 $3
#rm _$1.?

    